/*
Declare JavaScript Objects as Variables


Before we dive into Object Oriented Programming, let's revisit JavaScript objects.

Give your motorBike object a wheels, engines and seats attribute and set them to numbers.


var car = {
  "wheels":4,
  "engines":1,
  "seats":5
};

var motorBike = {

  // Only change code below this line.

};



*/


var car = {
  "wheels":4,
  "engines":1,
  "seats":5
};

var motorBike = {
  "wheels":2,
  "engines":1,
  "seats":2

  // Only change code below this line.

};
